sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - mkdir -p manager2/dist
  - docker build -t osallou/my .
  - npm install

script:
  - npm install -g mocha
  - npm install -g nyc
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose up -d
  - cd $TRAVIS_BUILD_DIR && sleep 180 && docker ps && nyc --all -x tests mocha
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose down
